// <auto-generated />
using Lab19_CreateAnAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lab19_CreateAnAPI.Migrations
{
    [DbContext(typeof(TodosDBContext))]
    [Migration("20181116062411_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lab19_CreateAnAPI.Model.Todo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("TodoListID");

                    b.HasKey("ID");

                    b.HasIndex("TodoListID");

                    b.ToTable("Todos");

                    b.HasData(
                        new { ID = 1, Description = "Wash all the clothes in the hamper", Name = "Wash Clothes", TodoListID = 1 },
                        new { ID = 2, Description = "Clean the toilet and bathtub", Name = "Clean Bathroom", TodoListID = 3 },
                        new { ID = 3, Description = "Take all trash bags to the dumpster", Name = "Throw Trash", TodoListID = 2 },
                        new { ID = 4, Description = "Clean all dust off dresser", Name = "Dust Dresser", TodoListID = 2 }
                    );
                });

            modelBuilder.Entity("Lab19_CreateAnAPI.Model.TodoList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("TodoList");

                    b.HasData(
                        new { ID = 1, Name = "Tre's Todo List" },
                        new { ID = 2, Name = "Shawn's Todo List" },
                        new { ID = 3, Name = "Lebron's Todo List" }
                    );
                });

            modelBuilder.Entity("Lab19_CreateAnAPI.Model.Todo", b =>
                {
                    b.HasOne("Lab19_CreateAnAPI.Model.TodoList")
                        .WithMany("Todos")
                        .HasForeignKey("TodoListID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
